version: '3.8'

services:
  app:
    build: .
    ports:
      - "12000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: